apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      service: mynginx
  template:
    metadata:
      labels:
        type: app
        service: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx

