apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      type: app
      app: backend
  template:
    metadata:
      labels:
        type: app
        app: backend
    spec:
      containers:
      - name: backend
        image: subicura/guestbook-backend:latest
        env:
        - name: PORT
          value: '8000'
        - name: GUESTBOOK_DB_ADDR
          value: 'mongo:27017'

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    type: app
    app: backend

