apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      type: app
      app: frontend
  template:
    metadata:
      labels:
        type: app
        app: frontend
    spec:
      containers:
      - name: frontend
        image: subicura/guestbook-frontend:latest
        env:
        - name: PORT
          value: '8000'
        - name: GUESTBOOK_API_ADDR
          value: 'backend:8000'

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    type: app
    app: frontend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
spec:
  rules:
  - host: guestbook.13.125.179.48.sslip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8000
