apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      app: nginx
  template:
    metadata:
      labels:
        type: app
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
